### PR TITLE
Fix compute node showing and sorting

### PR DESCRIPTION
**Pull request by hjhart**

### CODE REVIEW

**Comment by hjhart** [comment]
@kevinykchan I've seen your name come up from @bixu before on these PRs, hopefully we can get this merged. :)

**Comment by bixu** [comment]
@hjhart, you might want to check out Terraform and the Terraform Triton provider...

**Comment by bahamat** [comment]
Can you file an issue describing the problem you're trying to fix?

**Comment by hjhart** [comment]
@bahamat Issue created: https://github.com/joyent/knife-joyent/issues/98

**Pull request merged**
